service: slack-irasutoya

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: ap-northeast-1

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: "ANY {proxy+}"
    environment:
      CLIENT_ID: ${env:IRASUTOYA_CLIENT_ID}
      CLIENT_SECRET: ${env:IRASUTOYA_CLIENT_SECRET}
      VERIFICATION_TOKEN: ${env:IRASUTOYA_VERIFICATION_TOKEN}
plugins:
  - serverless-offline
